#! configuration/base.yaml
application:
  base_url: "http://127.0.0.1"
  port: 8000
  hmac_secret: "long-and-very-secret-random-key-needed-to-verify-message-integrity"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "cloud@ohmycloudy.uk"
  authorization_token: "POSTMARK_API_TEST"
  timeout_milliseconds: 10000
redis_uri: "redis://127.0.0.1:6379"
